name: Run Python Scripts on Push

on:
  push:
    branches: ["main"]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python scripts
        run: |
          for f in scripts/*.py; do
            echo "Running $f"
            python "$f"
          done
